/*
 * Music info
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SongDetail struct {

	ReleaseDate string `json:"releaseDate"`

	Text string `json:"text"`

	Link string `json:"link"`
}
