version: "3.6"
services:
  postgres:
    build: "./database"
    restart: "always"
    environment:
      POSTGRES_DB: "internalServer"
      POSTGRES_USER: "kulakov"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "3339:5432"