DROP TABLE IF EXISTS songs;

CREATE TABLE songs (
  "group" TEXT NOT NULL,
  song TEXT NOT NULL,
  release_date TEXT NOT NULL,
  text TEXT NOT NULL,
  "link" TEXT NOT NULL
);

INSERT into songs values ('Muse', 'Supermassive Black Hole', '16.07.2006',  'Ooh baby, don''t you know I suffer?\nOoh baby, can you hear me moan?\nYou caught me under false pretenses\nHow long before you let me go?\n\nOoh\nYou set my soul alight\nOoh\nYou set my soul alight\n\nGlaciers melting in the dead of night (ooh)\nAnd the superstars sucked into the supermassive (you set my soul alight)\nGlaciers melting in the dead of night\nAnd the superstars sucked into the (you set my soul)(Into the supermassive)\n\nI thought I was a fool for no one\nOoh baby, I''m a fool for you\nYou''re the queen of the superficial\nAnd how long before you tell the truth?\n\nOoh\nYou set my soul alight\nOoh\nYou set my soul alight\n\nGlaciers melting in the dead of night (ooh)\nAnd the superstars sucked into the supermassive (you set my soul alight)\nGlaciers melting in the dead of night\nAnd the superstars sucked into the (you set my soul)\n(Into the supermassive)\n\nSupermassive black hole\nSupermassive black hole\nSupermassive black hole\nSupermassive black hole\n\nGlaciers melting in the dead of night\nAnd the superstars sucked into the supermassive\nGlaciers melting in the dead of night\nAnd the superstars sucked into the supermassive\nGlaciers melting in the dead of night (ooh)\nAnd the superstars sucked into the supermassive (you set my soul alight)\nGlaciers melting in the dead of night\nAnd the superstars sucked into the (you set my soul)\n(Into the supermassive)\n\nSupermassive black hole\nSupermassive black hole\nSupermassive black hole\nSupermassive black hole\n', 'https://www.youtube.com/watch?v=Xsp3_a-PMTw');
INSERT into songs values ('Muse', 'Won''t Stand Down', '13.01.2022',  'I never believed that I would concede\nAnd let someone trample on me\nYou strung me along, I thought I was strong\nBut you were just gaslighting me\n\nI''ve opened my eyes, and counted the lies\nAnd now it is clearer to me\nYou are just a user and an abuser\nLiving vicariously\n\nI never believed that I would concede\nAnd get myself blown asunder\nYou strung me along, I thought I was strong\nBut now you have pushed me under\n\nI''ve opened my eyes and counted the lies\nAnd now it is clearer to me\nYou are just a user and an abuser\nAnd I refuse to take it\n\nWon''t stand down\nI''m growing stronger\nWon''t stand down\nI''m owned no longer\nWon''t stand down\nYou''ve used me for too long\nNow die alone\n\nNow I''m coming back, a counterattack\nI''m playing you at your own game\nI''m cutting you out, a shadow of doubt\nIs gonna hang over your name\n\nI''ve opened my eyes, I see your disguise\nI will never see you the same\nI know how to win, before you begin\nI''ll shoot you before you take aim\n\nNow I''m coming back, a counterattack\nA psychological war\nI''m cutting you in, I''m under your skin\nNow I''m gonna settle the score\n\nI''ve opened my eyes, I see your disguise\nI will never see you the same\nI know how to win, before you begin\nI''ll shoot you before you take aim\n\nWon''t stand down\nI''m growing stronger\nWon''t stand down\nI''m owned no longer\nWon''t stand down\nYou''ve used me for too long\nNow die alone\n\n(Won''t stand down)\n(Breaking out)\n(Won''t stand down)\n\nWon''t stand down\nI''m growing stronger\nWon''t stand down\nI''m owned no longer\nWon''t stand down\nYou''ve used me for too long\nNow die alone\n\n(Won''t stand down)\n(Won''t stand down)\n', 'https://www.youtube.com/watch?v=d55ELY17CFM');
INSERT into songs values ('Stone Sour', 'Through Glass', '22.07.2006',  'I''m looking at you through the glass\nDon''t know how much time has passed\nOh God, it feels like forever\nBut no one ever tells you that forever feels like home\nSitting all alone inside your head\n\n''Cause I''m looking at you through the glass\nDon''t know how much time has passed\nAll I know is that it feels like forever\nWhen no one ever tells you that forever feels like home\nSitting all alone inside your head\n\nHow do you feel? That is the question\nBut I forget you don''t expect an easy answer\nWhen something like a soul becomes initialized\nAnd folded up like paper dolls and little notes\nYou can''t expect a bit of hope\nSo while you''re outside looking in\nDescribing what you see\nRemember what you''re staring at is me\n\n''Cause I''m looking at you through the glass\nDon''t know how much time has passed\nAll I know is that it feels like forever\nWhen no one ever tells you that forever feels like home\nSitting all alone inside your head\n\nHow much is real? So much to question\nAn epidemic of the mannequins\nContaminating everything\nWe thought came from the heart\nIt never did right from the start\nJust listen to the noises\n(Null and void instead of voices)\nBefore you tell yourself\nIt''s just a different scene\nRemember it''s just different from what you''ve seen\n\nI''m looking at you through the glass\nDon''t know how much time has passed\nAnd all I know is that it feels like forever\nWhen no one ever tells you that forever feels like home\nSitting all alone inside your head\n\n''Cause I''m looking at you through the glass\nDon''t know how much time has passed\nAnd all I know is that it feels like forever\nWhen no one ever tells you that forever feels like home\nSitting all alone inside your head\n\nAnd it''s the stars\nThe stars that shine for you\nAnd it''s the stars\nThe stars that lie to you, yeah-ah\nAnd it''s the stars\nThe stars that shine for you\nAnd it''s the stars\nThe stars that lie to you, yeah-ah\n\nI''m looking at you through the glass\nDon''t know how much time has passed\nOh God, it feels like forever\nBut no one ever tells you that forever feels like home\nSitting all alone inside your head\n\n''Cause I''m looking at you through the glass\nDon''t know how much time has passed\nAll I know is that it feels like forever\nBut no one ever tells you that forever feels like home\nSitting all alone inside your head\nAnd it''s the stars\n\nThe stars that shine for you, yeah-ah\nAnd it''s the stars\nThe stars that lie to you, yeah-ah\nAnd it''s the stars\nThe stars that shine for you, yeah-ah\nAnd it''s the stars\nThe stars that lie to you, yeah, yeah\n\nWho are te stars\nWho are the stars, they lie\n', 'https://www.youtube.com/watch?v=GIzDsGyxsQM\n');h